version: 2.1

volumes:
  certs:
  nodered:

services:
  proxy:
    build: ./traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - certs:/var/certs
    labels:
      io.balena.features.balena-socket: true

  whoami:
    image: traefik/whoami
    labels:
#      traefik.http.routers.whoami.rule: Host("url")
#      traefik.http.routers.whoami.tls.certResolver: "letsencrypt"
      traefik.enable: true
      subdomain: whoami

  nodered:
    image: nodered/node-red:latest-12
    volumes: 
      - nodered:/data
    labels:
      traefik.enable: true
      subdomain: nodered
