[global]
checkNewVersion = false
sendAnonymousUsage = false

[log]
level = "$LOG_LEVEL"

[api]
insecure = true



[entryPoints]

[entryPoints.web]
address = ":80"


[entryPoints.web.http.redirections]

[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"


[entryPoints.websecure]
address = ":443"


[entryPoints.websecure.http]
middlewares = ["test-auth@file"]

[entryPoints.websecure.http.tls]
certResolver = "dnsWildcardMainDomain"


[[entryPoints.websecure.http.tls.domains]]
  main = "$MAIN_URL"
  sans = ["*.$MAIN_URL"]


[certificatesResolvers.letsencrypt.acme]
email = "$ACME_EMAIL"
storage = "/var/certs/acme-letsencrypt.json"

[certificatesResolvers.letsencrypt.acme.dnsChallenge]
provider = "$DNS_PROVIDER"
delayBeforeCheck = 0
resolvers = ["1.1.1.1:53", "8.8.8.8:53"]



[certificatesResolvers.dnsWildcardMainDomain.acme]
email = "$ACME_EMAIL"
storage = "/var/certs/acme-wildcardmaindomain.json"

[certificatesResolvers.dnsWildcardMainDomain.acme.dnsChallenge]
provider = "$DNS_PROVIDER"
delayBeforeCheck = 0
resolvers = ["1.1.1.1:53", "8.8.8.8:53"]



[providers.docker]
endpoint = "$DOCKER_HOST"
exposedByDefault = false
defaultRule = "Host(`{{ index .Labels \"subdomain\" }}.$MAIN_URL`)"

[providers.file]
directory = "/etc/traefik/conf.d"
